### ISSUE TITLE
DirectShowPlayerService::doRender: Unresolved error code 0x80040266 (IDispatch error #102)

### ISSUE THREAD

**Issue by Sriharshajasti123** [maralzar/Video-player#1]

**Comment by maralzar** [comment]
https://stackoverflow.com/questions/53328979/directshowplayerservicedorender-unresolved-error-code-0x80040266

**Comment by maralzar** [comment]
> 
> 
> _No description provided._

https://stackoverflow.com/questions/53328979/directshowplayerservicedorender-unresolved-error-code-0x80040266

**Comment by Sriharshajasti123** [comment]
Thank you so much
